name: To Do List Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Pengecekan kode
        uses: actions/checkout@v3

      - name: Print Pengecekan Kode
        run: echo "Cek kode dari ${{ github.repository }} pada branch ${{ github.ref }}"

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Print Setup Python
        run: echo "Setup Python versi 3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Print Install dependencies
        run: echo "Sukses menginstall dependencies"

      - name: Print Run linter
        run: echo "Mengecek kode menggunakan flake8 pada main.py"

      - name: Run linter
        run: |
          flake8 main.py

      - name: Print Run tests
        run: echo "Menjalankan unit tests menggunakan pytest"

      - name: Run tests
        run: |
          PYTHONPATH=. pytest tests/ --verbose

      - name: Upload Artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: main-script
          path: main.py
